modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Eltrut-Co/Totally-Wild/issues"
[[mods]]
modId="totally_wild"
version="1.0.0"
displayName="Totally Wild"
logoFile="totally_wild.png"
credits="8HP"
authors="Eltrut & Co."
description='''

'''

[[dependencies.totally_wild]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.totally_wild]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.totally_wild]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"